common: &common
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["DATABASE_NAME"] %>

development:
  <<: *common
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  pool: 5

test:
  <<: *common
  pool: 5

production:
  <<: *common
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  pool: 48
